set_property PACKAGE_PIN U18 [get_ports raw_rst]
set_property PACKAGE_PIN P19 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100mhz]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports raw_rst]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property PACKAGE_PIN R19 [get_ports vsync]
set_property PACKAGE_PIN J18 [get_ports {vgaBlue[3]}]
set_property PACKAGE_PIN K18 [get_ports {vgaBlue[2]}]
set_property PACKAGE_PIN L18 [get_ports {vgaBlue[1]}]
set_property PACKAGE_PIN N18 [get_ports {vgaBlue[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaBlue[0]}]
set_property PACKAGE_PIN D17 [get_ports {vgaGreen[3]}]
set_property PACKAGE_PIN G17 [get_ports {vgaGreen[2]}]
set_property PACKAGE_PIN H17 [get_ports {vgaGreen[1]}]
set_property PACKAGE_PIN J17 [get_ports {vgaGreen[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaGreen[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vgaRed[0]}]
set_property PACKAGE_PIN N19 [get_ports {vgaRed[3]}]
set_property PACKAGE_PIN J19 [get_ports {vgaRed[2]}]
set_property PACKAGE_PIN H19 [get_ports {vgaRed[1]}]
set_property PACKAGE_PIN G19 [get_ports {vgaRed[0]}]
set_property PACKAGE_PIN W5 [get_ports clk_100mhz]

set_property PACKAGE_PIN W19 [get_ports raw_down]
set_property PACKAGE_PIN T18 [get_ports raw_left]
set_property PACKAGE_PIN U17 [get_ports raw_right]
set_property PACKAGE_PIN T17 [get_ports raw_up]
set_property IOSTANDARD LVCMOS33 [get_ports raw_down]
set_property IOSTANDARD LVCMOS33 [get_ports raw_left]
set_property IOSTANDARD LVCMOS33 [get_ports raw_right]
set_property IOSTANDARD LVCMOS33 [get_ports raw_up]



set_property IOSTANDARD LVCMOS33 [get_ports switch]
set_property PACKAGE_PIN R2 [get_ports switch]